server:
  port: 20082

spring:
  application:
    name: foo-app
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.boot.autoconfigure.logging: ERROR

