server:
  port: 20083

spring:
  application:
    name: bar-app
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

#eureka:
#  instance:
#    prefer-ip-address: true
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    registry-fetch-interval-seconds: 2
#    healthcheck:
#      enabled: false
#    register-with-eureka: false

foo-app:
  ribbon:
    ServerListRefreshInterval: 1000
    listOfServers: localhost:20081,localhost:20082

ribbon:
  eureka:
    enabled: false
  eager-load:
    clients: foo-app

org.springframework.boot.autoconfigure.logging: ERROR
