server:
  port: 20082

spring:
  application:
    name: msa-bar-app
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

sample:
  zipkin:
    enabled: true

org.springframework.boot.autoconfigure.logging: ERROR

